### ISSUE TITLE
Generate a thumbnail.png from a provided screenshot.png

### ISSUE THREAD

**Issue by mwilliams2014** [liferay/liferay-js-themes-toolkit#103]
The screenshot.png should be in the theme's `src/images` folder. Perhaps we can generate a dummy one that the user can simply replace.
The user's screenshot.png should match the dimensions: 1080px x 864px
The generated thumbnail.png should match the dimensions: 150px x 120px

**Comment by mwilliams2014** [comment]
@jbalsas , I know this was opened 6 months ago, but I'm updating the docs for 7.2 and wanted to put this back on your radar.

**Comment by wincent** [comment]
Naïve question: could we just teach `generator-liferay-theme` to copy a totally generic placeholder image into the created theme? (ie. not generate anything; just provide a totally standard placeholder).

![placeholder-2000x1440-300x216](https://user-images.githubusercontent.com/7074/55859016-6971ab80-5b71-11e9-996c-42059d7208b5.png)

or:

![download](https://user-images.githubusercontent.com/7074/55859055-80b09900-5b71-11e9-87ed-a5fac5be08c8.png)

etc

**Comment by jbalsas** [comment]
Yeah, the initial idea was to simply provide a basic placeholder. 

@victorvalle, what do you think? could you provide some visuals for this?

@mwilliams2014, I don't understand the relation with the Gradle Plugin at all... how do these 2 connect?

**Comment by mwilliams2014** [comment]
@jbalsas The gradle plugin expects a screenshot.png and generates a thumbnail.png from that I believe. So it's the same across the board for devs, regardless of the environment they choose to develop their theme in (theme gradle plugin or theme generator), the idea would be to require them to provide a screenshot.png for either, then one of the theme tasks or something else would generate the thumbnail.png from the screenshot.png, similar to what the theme gradle plugin does.

The idea is consistency between the two approaches to theme development. There was confusion with this for a customer who went from the theme gradle plugin to the theme generator. They were expecting to create a screenshot.png. And of course when they deployed their theme with the liferay theme tasks, their thumbnail didn't show because it expected a thumbnail.png. This would fix that confusion.

Does that make sense?

**Comment by victorvalle** [comment]
Hi @mwilliams2014  the new images only need to be 480x270. The change from 4:3 to 16:9 and the card maximum width force us to this value.

**Comment by mwilliams2014** [comment]
Ah, ok. Thanks for letting me know @victorvalle ! I'll update the 7.2 docs to reflect this. Is this backported to 7.0 as well, or just for 7.2?

**Comment by mwilliams2014** [comment]
@victorvalle is this required for color schemes as well? The thumbnails are not responding the same way for color schemes. It appears to be broken:
![Screenshot (375)](https://user-images.githubusercontent.com/7050434/55905534-27ac2980-5ba0-11e9-93de-8ff8bdb286a6.png)

**Comment by marcoscv-work** [comment]
Hey @mwilliams2014 I think that is a bug, a really ugly one..
We will fix it to match new sizes

**Comment by marcoscv-work** [comment]
By the way and about screenshot.png, where do we use this image? Do we really need it? I think the only essential image is the thumbnail

**Comment by marcoscv-work** [comment]
https://issues.liferay.com/browse/LPS-93806

**Comment by izaera** [comment]
We have decided to go with the thumbnail.png approach. We will provide a default thumbnail.png so that users know where it should be placed and what size it should have and then users can change it at their will.

Transforming a screenshot adds complexity and we don't see much benefit given that theme devlopers are usually design aware people, capable of creating their own thumbnails.

**Comment by mwilliams2014** [comment]
The issue wasn't that users didn't know how to create a thumbnail.png. The issue was consistency between the theme builder gradle plugin and the theme generator. The gradle plugin expects a screenshot.png that it then creates a thumbnail.png from. The theme generator just expects a thumbnail.png. This caused an issue when a customer moved from the gradle plugin to the theme generator. They expected it to use the screenshot.png as well. Consistency should be the goal.

**Comment by jbalsas** [comment]
Hey @mwilliams2014, while we agree with consistency being a good thing, consistency for the sake of consistency is not always good.

We can't match one to one whatever other team is doing... I'm sure the js-toolkit has a lot of features the Gradle plugin doesn't (which might prompt customers to migrate to it) and which they won't be implementing either because it does not make sense in the context of the tool or because it's too expensive.

That's the case for this. If we want, we can document the difference for those migrating from one tool to the other and viceversa.

**Comment by mwilliams2014** [comment]
Understandable @jbalsas, just that that was the original goal of this issue when I created it. The work around is already documented, so we're good in that regard. This definitely was an edge case I think for the customer. A placeholder will still be helpful, so this improves usability and removes the chance for user error, which is still a win :-)
