### ISSUE TITLE
gulp watch not taking correct version number

### ISSUE THREAD

**Issue by schwaaab** [liferay/liferay-js-themes-toolkit#107]
Gulp Watch with liferay-theme-tasks 7.0.0 does not consider the version number in package.json. Instead always creates a theme with version 1.0.0. Therefore after ending gulp watch and after a new gulp deploy two themes with different versions are active.

Problem occurs on linux with liferay 7.0.x

**Comment by wincent** [comment]
We have significantly changed the watch implementation in #190 with the hope of fixing the existing issues. At the time of writing, that's in the "master" branch and will be included in the next release (v8.0.0-rc.4). The master issue for tracking the rewrite is #127, so I am going to close these separate tickets and ask that we consolidate further discussion about watch there.
