### ISSUE TITLE
Make `watch` task more robust

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-js-themes-toolkit#127]
Our `watch` task currently depends on the `gogo` shell being available and enabled in a running instance of Liferay Portal. This has proven to be a bit unstable and unreliable over time. 

We should try to investigate new alternatives or ways to provide this that don't necessarily depend on deploying bundles to Liferay.

One option could be to have some type of dev-server (webpack or standalone) so we could simply proxy the updated css files on request

**Comment by wincent** [comment]
Going to close this now that #190 and #201 are in, along with #209.
