### ISSUE TITLE
Upgrade to Gulp v4

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-js-themes-toolkit#148]
~Necessary prerequisite to solve:~ https://github.com/liferay/liferay-themes-sdk/issues/97

This one is the largest subtask in https://github.com/liferay/liferay-js-themes-toolkit/issues/199 — master ticket for dealing with dependency security issues. See that ticket for information on the overall prioritization/urgency of performing this upgrade.

**Comment by wincent** [comment]
Having looked into this further now, I see we will (probably) have to update https://github.com/jbalsas/liferay-plugin-node-tasks to v4 as well as a prerequisite. I created an internal ticket (https://issues.liferay.com/browse/IFI-553) for moving that repo under the "liferay" org on GitHub, which we may as well do at the same time.

Some more research notes on the relationship between "liferay-js-themes-toolkit" and "liferay-plugin-node-tasks" over here: https://github.com/liferay/liferay-js-themes-toolkit/pull/192/commits/b5730f1edec1f9926c816491bed4084d3cc0ec92

> - "liferay-theme-tasks" depends on "liferay-plugin-node-tasks".
> - Both register a "build" task, so one clobbers the other, I think (concretely, I think "liferay-theme-tasks" registers the tasks from "liferay-plugin-node-tasks" and then overwrites the latter's "build" with its own).
> - "liferay-theme-tasks" ends up calling "liferay-plugin-node-tasks" in a couple of places; for example, "deploy:gogo" will invoke "plugin:deploy-gogo", "deploy:war" will invoke "plugin:deploy" etc.
> - Those plugin tasks depend on "build", but due to the overwriting mentioned above, I *think* they actually end up calling the theme tasks version of "build", which has already run at that point, and at least under Gulp v3 (I *think*) won't run again.
> - https://www.npmjs.com/package/liferay-plugin-node-tasks claims that "liferay-plugin-node-tasks" lives at: https://github.com/Robert-Frampton/liferay-plugin-node-tasks but it actually lives at: https://github.com/jbalsas/liferay-plugin-node-tasks (we should correct that link in the next release and ideally move this into the "liferay" GitHub org).

**Comment by wincent** [comment]
Minor update to the above: rather than updating "liferay-plugin-node-tasks" as a prequisite to updating this repo,  decided to fold it into this repo first; it will no longer be an independent package, but rather part of "liferay-theme-tasks". https://github.com/liferay/liferay-js-themes-toolkit/issues/193 is the issue for that.

**Comment by jbalsas** [comment]
Adding this to #415. I think we can either update go gulp v4 or attempt to remove our gulp dependency alltogether as part of a bigger rewrite.

Thoughts @izaera, @wincent?

**Comment by wincent** [comment]
Moving to Gulp v4 will be a fairly big task because the API is quite different compared to v3, but not as big as a full rewrite (which itself would entail a pretty big risk of regressions compared to a version upgrade). So — in the absence of a time machine to go back and steer clear of Gulp in the past — I'd be inclined towards updating instead of rewriting. I think it will be less work, and less risk.

Having said that, moving to v4 is a potentially a breaking change for users who have written their own custom Gulp tasks which depend on toolkit tasks. https://github.com/liferay/liferay-js-themes-toolkit/issues/381 (adding scripts to run bundled Gulp instead of global one) is useful because at least it provides us with a pathway towards *forcing* the use of a specific version, but either way we have a breaking change which will have to be thoroughly documented.

**Comment by jbalsas** [comment]
In light of https://github.com/gulpjs/gulp/issues/2146 and https://github.com/nodejs/node/issues/19786, we could sideline this for a little while and just restrict our Node support to <v10, but that feels a bad option as well... :(

**Comment by izaera** [comment]
Revisiting this because of #444, I would now vote for removing gulp completely. In the end will make the code more legible and simpler. 

And, because updating to v4 will break user tasks anyway (as per [the comment above](https://github.com/liferay/liferay-js-themes-toolkit/issues/148#issuecomment-573573718)) this issue is a good excuse to get rid of gulp.

**Comment by jbalsas** [comment]
Not sure if [this article](https://codeburst.io/switching-to-gulp-4-0-271ae63530c0) is too naive about the migration, but it states:

> Migration to gulp@4.0 should be pretty straightforward.

Similar thoughts are collected [here](https://www.sitepoint.com/how-to-migrate-to-gulp-4/) and [here](https://medium.com/@defrian.yarfi/https-medium-com-defrian-yarfi-upgrade-gulp-3-to-gulp-4-the-gulpfile-js-workflow-45196e333b86). They all mention the introduction of `series` and `parallel` as the main hurdles...

Based on @wincent's comments and the growing pressure to support Node 12 LTS... I'd be willing to give Gulp4 a try before considering a bigger rewrite.

@izaera, could you put some time into it, if anything to clarify how hard could it be?

**Comment by wincent** [comment]
To clarify my previous comment:

> Moving to Gulp v4 will be a fairly big task

We've done a similar v3 to v4 rewrite in other projects (example: [in AlloyEditor](https://github.com/liferay/alloy-editor/pull/982)). It's not difficult, but *that* PR does an update in a repo that used Gulp only lightly for its own build — `liferay-theme-tasks` on the other hand, has a much larger exposure to Gulp, and migrating it will be more work.

**Comment by izaera** [comment]
I have labeled this as feature because it will introduce breaking changes and will change the way the project is consumed by outside users.
