### ISSUE TITLE
Clarify "compatibility matrix" between versions of liferay-js-themes-toolkit and Liferay DXP

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-js-themes-toolkit#184]
At the moment the current release (v8.0.0-rc.3) provides varying degrees of support for different versions of Liferay DXP; for example:

- You can create new themes for Liferay DXP 7.0. or 7.1 (and on the unreleased "master" branch, you can also create 7.2 themes, which are basically the same as 7.1 themes but depending on "liferay-theme-deps-7.2" instead of "liferay-theme-deps-7.1").
- There are upgrade tasks for going from 6.2 to 7.0, and from 7.0 to 7.1.
- "liferay-theme-tasks" offers a huge number of tasks that can be used inside themes, but unfortunately it builds on Gulp v3 which currently has a lot of insecure dependencies (as identified by `npm audit`/`yarn audit`) and is API-incompatible with Gulp v4.

With the release of DXP 7.2 our "compatibility" matrix becomes more complicated because, if we decide to continue down the same path we've been on so far, all of those "liferay-theme-tasks" will now have to be aware of *four* versions of DXP (6.2, 7.0, 7.1, 7.2) and we'll additionally need a new 7.1-to-7.2 upgrade functionality.

What I'd like to propose here is the following:

- Draw a line in the sand and cut v8.0.0 final from the existing v8.0.0-rc3 base; this version will support the features listed at the top (ability to upgrade a theme from 7.0 to 7.1, ability to create themes for 7.0 and 7.2 etc). Call this the "8.x-stable" branch and only apply bugfixes to it.
- On "master", prepare a new v9.x series which will drop support for some of the older features which are causing maintenance overhead; for example:
  - v9 would be able to:
    - Create themes for DXP 7.2 (only!).
    - Upgrade a DXP 7.1 theme to DXP 7.2.
  - v9 would *not* be able to:
    - Create themes for 7.0 or 7.1.
    - Upgrade themes from 6.2 to 7.0, or from 7.0 to 7.1.
  - Additionally, v9 will work exclusively with Gulp v4 (we *may* be able to provide some kind of shim to expose the tasks to somebody running Gulp v3, but I am not sure if that is feasible).

Basically, the idea would be that if you want to create a new theme from scratch, you download v9 of "generator-liferay-theme" and use it. If you want to upgrade a 7.1 theme to 7.2, you update you "liferay-theme-tasks" dependency to v9 and use it.

Conversely, if you want to create a theme for an older version of DXP (7.0 or 7.1), you download v8 of the generator and use it. If you want to do a 6.2-to-7.0 or a 7.0-to-7.1 theme upgrade, then you keep on using v8 of "liferay-theme-tasks".

It's true that we would have to document this very carefully. Additionally, we could perhaps add some prompts in the output of the v8 generator and  theme tasks letting people know how to generate 7.2 themes or upgrade themes to 7.2. Personally, I think it would be worth doing this because it would reduce the maintenance burden to the point where we can simplify the project, eliminate bugs, and focus on producing a very high-quality, streamlined tool that does a smaller number of things but does them very well.

**Comment by yuchi** [comment]
I second @wincent on the problem statement. _But_ DXP (aka EE) lifecycle is to be kept in mind: v9 will be released when DXP 7.0 will still have paid subscriptions and support, so it is strange to have it limited for 7.2. If you are really going to backport fixes to 8.x then it’s ok, but personally I can’t anticipate the amount of work you need to put to follow along with Service/Fix Packs releases.

That said, some clearance is much overdue.

**Comment by wincent** [comment]
We (@julien, @jbalsas and I) reviewed the proposed changes in #187 and concluded that it is probably the right approach, so I am going to close this one.

In summary:

- We have a replacement for the "watch" functionality that we will soon merge (#190) into the master branch. There have been about 100 commits since the last v8.0.0-rc.3 release, including a couple of bug fixes (eg. #139, #140) that people will be keen to get their hands on. This, together with "watch", will make this an important release.
- We'll proceed with a v9 release that drops support for older versions. #187 currently includes documentation, prompts and other aids to let people know which versions it supports and how to use v8 in order to work with older versions. People perform major DXP updates infrequently, and updating themes is probably only about 15% of the work (people are more likely to create a new theme from scratch to update their branding to coincide with a major release, because it is such a large and infrequent undertaking anyway), so we want to strike the right balance: we currently have a complicated tool that is brittle and hard to change because it tries to be too many things to too many people; we can make a higher quality tool moving forward if we narrow its focus, and we can mitigate the pain by providing good guidance about which version to use.
- In the more distant future (eg. when the future annual DXP releases come out 7.3, 7.4 etc), we can evaluate whether to cut major versions of the toolkit (which will be v10, v11 etc), but the truth is that we don't expect major changes to be made to themes moving forward because the yearly cadence means that such changes are going to be more incremental in nature; this in turn means that we probably won't need to make major versions and can support them on the v9 line of development. This is in contrast to previous cycles like 6.2 to 7.0 and 7.0 to 7.1 which were elaborated over a much longer period and were much more invasive in terms of the changes involved. As such, we think that v8/v9 is a strategically useful moment to try to make a major break, but it is unlikely we'll need to do so again in the foreseeable future.
