### ISSUE TITLE
Rename to liferay-js-themes-toolkit

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-js-themes-toolkit#185]
We probably don't want to rename the actual repo so as not to break bookmarks (or maybe we do, I don't know if GitHub makes it possible/easy to redirect people), but at least in terms of the documentation and internal terminology we want to rebrand this as "a themes toolkit" as opposed to an SDK because it is closer in spirit to a toolkit than a set of APIs, and it's a pattern we've been following in other places, according to what I've heard from @jbalsas.

**Comment by wincent** [comment]
> I don't know if GitHub makes it possible/easy to redirect people

According to [the docs](https://help.github.com/en/articles/renaming-a-repository), redirects will take effect automatically if we rename the repo.

**Comment by wincent** [comment]
Repo has been renamed now; once the in-flight PRs land, will do a follow-up pass through to make sure all the internal references are updated. (For example, in my first pass at this I change "liferay-themes-sdk" to "liferay-themes-toolkit", but the final name that we settled on is "liferay-js-themes-toolkit".)

**Comment by yuchi** [comment]
Now we have to fix all our training slides :)

**Comment by wincent** [comment]
Yes @yuchi, although the good news is that the old URLs will still work in the meantime (even `git clone` etc will work with the old URLs).

**Comment by wincent** [comment]
Closing this one because it is basically done on both the v8 (#197) and v9 branches (68b92f3af767f6511d0).
