### ISSUE TITLE
"upgrade" Gulp task: missing file headers in css.diff

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-js-themes-toolkit#205]
I am not sure if this is still an issue, but it was originally reported here:

https://github.com/liferay/liferay-theme-tasks/issues/44

and mentioned in:

https://github.com/liferay/liferay-js-themes-toolkit/issues/48

I just added a PR that closes #48:

https://github.com/liferay/liferay-js-themes-toolkit/pull/203

so I am creating this issue to reflect the open question about whether the originally reported issue is resolved.

I won't paste the original text in as it is rather long, and I'm not actually sure how to summarize it. @blzaugg might be able to provide some more clarity on exactly what would be required?

**Comment by blzaugg** [comment]
Whoever wrote that original ticket should sit in a corner, and think about what they've done.

I believe what I was after is...

All other "file headers" look like:
```
Index: file-name.ext
===================================================================
--- file-name.ext	Original File
+++ file-name.ext	Updated File
```

But for some reason `custom.css` or `custom.scss` is just:
```
===================================================================
--- file-name.ext	Original File
+++ file-name.ext	Updated File
```
```

I'm not sure if this is still an issue.

**Comment by wincent** [comment]
We've just migrated this project to [the `liferay-frontend-projects` monorepo](https://github.com/liferay/liferay-frontend-projects) in the name of consolidation. As this issue is quite old now, I'm not going to transfer it automatically. If you consider it to be still relevant, please [create a fresh issue over in the new repo](https://github.com/liferay/liferay-frontend-projects/issues/new?labels=js-themes-toolkit&template=js-themes-toolkit.md).
