### ISSUE TITLE
Send the correct MIME type header when watching

### ISSUE THREAD

**Issue by julien** [liferay/liferay-js-themes-toolkit#208]
When we serve "theme" assets with `gulp watch`, css files don't have the correct MIME type, this doesn't seem to be a huge issue but it might be better to send it correctly.

**Comment by wincent** [comment]
Removed the beta.4 label because that is a previous release, these are the tags we have right now (as per `git tag -l`); seems we don't have corresponding GitHub issue labels for most of them:

```
v8.0.0-alpha.1
v8.0.0-alpha.2
v8.0.0-alpha.3
v8.0.0-alpha.4
v8.0.0-alpha.5
v8.0.0-alpha.6
v8.0.0-beta.0
v8.0.0-beta.1
v8.0.0-beta.2
v8.0.0-beta.3
v8.0.0-beta.4
v8.0.0-beta.5
v8.0.0-rc.0
v8.0.0-rc.1
v8.0.0-rc.2
v8.0.0-rc.3
```

**Comment by wincent** [comment]
Was closed by https://github.com/liferay/liferay-js-themes-toolkit/pull/209
