### ISSUE TITLE
Improvement:  stop generating the favicon.ico in images folder on every build

### ISSUE THREAD

**Issue by LucyI** [liferay/liferay-js-themes-toolkit#231]
**Issue:** We delete the favicon.ico file that's included with the initial build, but it is replaced on every build. 

**Why this is important:** this set up does not allow for any other favicon path. 

**Details:** We are using a single theme to provide related themes for different sites. Each site has its own favicons and logos that are placed in brand folders within the images folder. So the brand folders serve each site's favicon. But when there's a favicon file in the outer images folder this file often gets picked up by browsers instead of the favicon specific to that site. Our workaround is to unzip the war file and remove the default favicon each time before deploying. 

 I think it's helpful to have the favicon file initially, but once deleted it would be great if it could stay deleted...

**Comment by wincent** [comment]
My suggestion here would be to delete the top-level favicon using a gulp hook.

If you look in your generated theme the favicon is probably coming from `./node_modules/liferay-frontend-theme-unstyled/images/favicon.ico`, and it is getting copied every time thanks to the `build:base` gulp task:

https://github.com/liferay/liferay-js-themes-toolkit/blob/6b5151d2173080b9eabdab4e9cf86b6693d1f9e9/packages/liferay-theme-tasks/tasks/build.js#L98-L105

So, the solution is to add a hook that runs *after* that task to clean up the unwanted file; something like this in the gulpfile.js:

```javascript
const fs = require('fs');
const path = require('path');

liferayThemeTasks.registerTasks({
	gulp: gulp,
	hookFn: function(gulp) {
		gulp.hook('after:build:base', function(done) {
			fs.unlinkSync(path.join(__dirname, 'build/images/favicon.ico'));
			done();
		});
	},
});
```

**Comment by LucyI** [comment]
Thanks that does work. For anyone needing the same fix: I used the asynchronous function **fs.unlink** rather than the synchronous fs.unlinkSync.
