### ISSUE TITLE
Dependency on liferay-theme-deps-* packages complicates theme handling

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-js-themes-toolkit#24]
We've traditionally had some problems with `liferay-theme-deps-*`. Specially in regards to change granularity. Since everything is hidden in there, it's hard to pick different versions of themes and prevent unwanted updates to happen. 

For example, I was trying to update `westeros-bank` and this is all I need as depdencies:
- `gulp@3.9.1`
- `gulp-sass@4.0.1`
- `liferay-frontend-theme-styled@3.0.3`
- `liferay-frontend-theme-unstyled@3.0.4`
- `liferay-theme-tasks@8.0.0-beta.1`
- `liferay-theme-deps-normalize@8.0.0-beta.1`

My suggestion is to deprecate those packages and update the generator to generate the necessary dependencies rather than the fixed `liferay-theme-deps-${liferayVersion}`.

What do you think, @natecavanaugh, @marcoscv-work?

**Comment by mwilliams2014** [comment]
I second this. I'm working on the theme upgrade docs, and when trying to build my files, I noticed the base files were out of sync. I had to manually lookup the latest version of the styled and unstyled  theme and install them to make it work. It would be a lot easier to develop if we could see the versions as @jbalsas pointed out.

**Comment by wincent** [comment]
Effectively done as part of #187.
