### ISSUE TITLE
`gulp watch` not auto deploying saved changes

### ISSUE THREAD

**Issue by john-co** [liferay/liferay-js-themes-toolkit#259]
**Steps to reproduce:**
1. Obtain generated liferay theme (ie: generated 7.2 theme from yo liferay-theme)
2. Make an edit to a file on src/css/*.scss 
ie:
```
html body {
    background-color:green;
}
```
3. Run `gulp deploy`
4. Add the following line to portal-ext.properties: `include-and-override=portal-developer.properties`
5. Start liferay instance
6. Apply theme to public pages
7. Assert color green background change in dom and/or page
8. Navigate to theme’s root folder
9. Run `gulp watch`
10. Make an edit to a file on src/css/_custom.scss
ie:  
```
html body {
    background-color:red;
}
```
11. Save .scss file

**Actual Result:**
Assert no auto-deployment and no change to public pages

**Expected Result:**
Changes autodeployed, and can assert green background and DOM that green has changed to red.

**Comment by zhangyan0701** [comment]
Got the same result when testing with Toolkit v8.0.1 on 7.0/7.1 theme.

**Comment by wincent** [comment]
@julien: what do you think of this?

In both v8 with a 7.0/7.1 theme and v9 with a 7.2 theme, `gulp watch` should open a browser window to a proxied instance of the portal running on port 9080. This is distinct from the standard local port of 8080; only on the proxied port should live-reloading have effort.

@john-co, @zhangyan0701: What's the browser address bar show?

**Comment by julien** [comment]
@wincent I agree, only the proxied port should have live-reload enabled.

**Comment by zhangyan0701** [comment]
@wincent 
For v8.0.3 with 7.0/7.1 theme, run 'gulp watch' opens a window with url: http://localhost:9080/, and the changes take effect on this proxied port. Thank!

**Comment by wincent** [comment]
Thanks for confirming that @zhangyan0701. I think this means that things are working but we probably at least need to:

1. Update our test plans; and
2. Update our documentation (cc @mwilliams2014):

to ensure that people know to connect to port 9080 in order to get watch with live reloading working. It may be that the "automatically open a browser window with the right URL in it" is not *quite* enough to make it obvious that watch works only on that port. It is pretty easy to accidentally open a new portal instance via a bookmark or some other means that uses the other port.

**Comment by mwilliams2014** [comment]
Ah, ok. I don't believe that was always the case, but could just be an oversight on my part. I'll update our docs to note that. Thanks!

**Comment by wincent** [comment]
@mwilliams2014: AFAIK the first time we mentioned port 9080 in this repo was in 327cab7abe353f9bd7f4306c1c9363dae18754e5 (March 2018), but I don't know much about how it worked back then (it might not have worked all that well, to be honest). 3a1f549dfd29fa6 (this month) is the commit that completely changed the watch implementation.

**Comment by mwilliams2014** [comment]
Just tested for a 7.1 theme on 8.0.0-rc.3, it prints this proxy info at the end of the gulp watch task:
```
[Browsersync] Proxying: http://localhost:8080
[Browsersync] Access URLs:
 ---------------------------------
    Local: http://localhost:9080
 External: http://192.168.2.3:9080
 ---------------------------------
```
I'll add the note to the docs as well so it's more clear.

**Comment by mwilliams2014** [comment]
Sent https://github.com/sez11a/liferay-docs/pull/4004
