### ISSUE TITLE
Support `gulp extend` without npm search

### ISSUE THREAD

**Issue by lgdd** [liferay/liferay-js-themes-toolkit#266]
When using _Artifactory_ as your npm registry (and proxy registry), `gulp extend` is not working because _Artifactory_ doesn't support npm search syntax yet. Therefore, a feature request has been opened on _JFrog_: https://www.jfrog.com/jira/browse/RTFACT-18655 (any upvote is welcome).

In the meantime, we could maybe add some support to avoid using npm search and refer directly to a package URL. This is just an idea to start a conversation around this issue.

Thanks :^)

**Comment by OlivierNeu** [comment]
We actually encounter this problem in our environment. In fact, this is a stumbling block only in the build of our themes in our Concourse Delivery tools. The solution of directly referencing the url of our thongs for example would effectively solve our problem while remaining agnostic of the storage solution.

**Comment by wincent** [comment]
I have a draft for this started in: https://github.com/liferay/liferay-js-themes-toolkit/pull/332

**Comment by wincent** [comment]
v9.x verision of the PR is https://github.com/liferay/liferay-js-themes-toolkit/pull/333
