### ISSUE TITLE
watch mode CSS and JS changes don't actually get deployed

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-js-themes-toolkit#302]
In #291 we reported that non-JS/CSS changes weren't getting deployed to the server.  As described in #297, this is because our `deploy:file` and `deploy:folder` implementations weren't working at all. It turns out that even JS/CSS changes weren't really getting deployed either — our live-reloading proxy just gives the illusion that they are (if you visit on the non-proxied port 8080 you'll see that the changes aren't really there) — because the CSS watching code used the same broken `deploy:file` mechanism, and the JS watching code didn't even try.

Fixing this is probably pretty low priority because in #299 we do an auto-deploy whenever we start watching, which makes it less likely that people will see a stale theme, and the workaround is pretty self-evident: if you don't see the theme as you would expect it is pretty straightforward to deploy it. So this might end up being just a documentation fix that makes it clear that "watch" is a tool for visualizing changes under development, but it shouldn't be considered a full-fledged replacement for deploying a theme.

**Comment by mwilliams2014** [comment]
Sorry @wincent  Didn't see the documentation label. Wasn't aware there was one. No one said. I'll see how we can update the docs to make this more clear.

**Comment by mwilliams2014** [comment]
Sent https://github.com/sez11a/liferay-docs/pull/4420 and https://github.com/sez11a/liferay-docs/pull/4421. Hopefully that will make it clear.

**Comment by wincent** [comment]
> Sorry @wincent Didn't see the documentation label. Wasn't aware there was one. No one said.

And with this, you have passed the test, my young padawan. Everything is proceding as I had foreseen it.

![emperor-palpatine-1555323736](https://user-images.githubusercontent.com/7074/61658410-959add80-acc5-11e9-99ba-defa409b1b98.jpg)

Seriously though, this was really just a reminder that I made and I didn't have a clear idea for when we should do it; and the "documentation" label isn't something that we've rigorously applied, but maybe we should.

**Comment by wincent** [comment]
We've just migrated this project to [the `liferay-frontend-projects` monorepo](https://github.com/liferay/liferay-frontend-projects) in the name of consolidation. As this issue is quite old now, I'm not going to transfer it automatically. If you consider it to be still relevant, please [create a fresh issue over in the new repo](https://github.com/liferay/liferay-frontend-projects/issues/new?labels=js-themes-toolkit&template=js-themes-toolkit.md).
