### ISSUE TITLE
Gulp Watch doesn't let you sign in on proxy port

### ISSUE THREAD

**Issue by mwilliams2014** [liferay/liferay-js-themes-toolkit#309]
Steps to reproduce (tested on Chrome with custom theme):
1. run gulp watch
2. Open proxy Port:9080
3. click sign in link

Expected: portal signs in

Actual: it just hangs at `http://localhost:9080/c/portal/login?p_l_id=20129`

Nothing in the tomcat log or browser console

As soon as I sign in to port:8080 I can go back on port:9080 and navigate the portal as signed in

**Comment by wincent** [comment]
Should be fixed in [v8.0.8](https://github.com/liferay/liferay-js-themes-toolkit/releases/tag/v8.0.8) and [v9.1.1](https://github.com/liferay/liferay-js-themes-toolkit/releases/tag/v9.1.1).
