### ISSUE TITLE
Teach "upgrade" task to add gulp hook that copies font-awesome fonts

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-js-themes-toolkit#321]
Basically need a hook like the one you can see [here](https://github.com/brianchandotcom/liferay-portal/pull/71324/commits/37814ed4df1c413716d04f9cd48fb995c08b9bee) because liferay-frontend-theme-unstyled no longer brings font-awesome and glyphicons with it. They're still available in the liferay-font-awesome package, but you have to arrange to copy them into your theme and make sure you're importing them with the correct path.

**Comment by jbalsas** [comment]
This was added back in https://github.com/liferay/liferay-js-themes-toolkit/pull/382
