### ISSUE TITLE
Add support to overwrite _rtl.ccs files that generate with build:r2 task

### ISSUE THREAD

**Issue by naderjafari** [liferay/liferay-js-themes-toolkit#330]
At the moment, all css files converted to RTL with build:r2 task and we can not overwrite this files anyway.
in liferay modules we can overwrite _rtl.css files by add a files name like this :
for overerite main_rtl.css we can add a css file with name main_rtl.scss and all rules in this file prepend to main_rtl.css that converted automatically to rtl.

in liferay theme we need this way to overwrite _rtl.css files.
i add some change in build:r2 and i want to commit this changes to add this ability to theme builder :

```
liferayThemeTasks.registerTasks({
	gulp: gulp,
	hookFn: function(gulp,options) {
		const {pathBuild} = options;
		gulp.task('build:r2', function(done) {
			const r2 = require('gulp-liferay-r2-css');
			const plugins = require('gulp-load-plugins')();
			const fs = require('fs');

			return gulp
				.src([pathBuild + '/css/*.css','!'+pathBuild+'/css/*_rtl.css'])
				.pipe(plugins.rename({
					suffix: '_rtl',
				}))
				.pipe(r2())
				.pipe(map(function (file, cb) {
					fs.stat(file.path, function(err, data) {
						if (!err) {
							var content = fs.readFileSync(file.path, 'utf8');
							file.contents = Buffer.from(file.contents.toString('utf8').concat(content));
						}
					});
					cb(null, file);
				}))
				.pipe(gulp.dest(pathBuild + '/css'));
		});

	}
});
```

**Comment by jbalsas** [comment]
I agree this is a rather obscure pattern, but it is indeed present in other parts of the product, so one could argue we should implement it here for consistency.

@naderjafari, thanks for your patience here. I want to make sure we get this right.

In https://github.com/liferay/liferay-js-themes-toolkit/issues/330 you detail the solution you're currently applying, but it's unclear what's exactly the problem. Could you please just expand a bit on that for me?

If I understand correctly, you want a way to override specific RTL changes that are made automatically. My concern is that this behaviour "prepends" code. For a CSS override (if that's the use case), shouldn't it append them instead?

Could you also maybe add some examples of things that are not working properly with the currently automatic system so we can attempt to figure out if there's some general gap that we might be missing?

Thanks!

**Comment by wincent** [comment]
I agree that it would be helpful to have more context about what kinds of overrides @naderjafari needs to make.

On the prepend vs append thing, my reading of the code is that it *appends*:

```javascript
// Append overrides to content.
file.contents = Buffer.from(
	file.contents
		.toString('utf8')
		.concat(fs.readFileSync(file.path, 'utf8'))
);
```

basically, takes the existing file content and then `concat`s the override content to it.

**Comment by naderjafari** [comment]
Thank you @jbalsas .
In this example that is my real use case the automatically convert does not work properly : 

- 1. In Liferay-theme-generator create a theme and set the base to styled theme.
- Deploy your theme 
- Create a KB Article with a `code` element in the content field like bellow
`<pre><code">$ git init</code></pre>`

- Place this article in a page With KB Article Display Portlet and change the theme to your deployed theme .

- in LTR languages everything is fine But in RTL languages we want to write  CSS Rules like bellow to show codes in this element like LTR mode so we need to write this CSS rules : 
`code, kbd, pre, samp {
    text-align: left;
    direction: ltr;
}
`
- if we write these Rules in _custom.css all of this rules Convert by build:r2 task and will change to : 
`code, kbd, pre, samp {
    text-align: right;
    direction: rtl;
}
`
But if we have an option to override main_rtl.css we can add Correct rules.
- generally, we need this feature to override Wrong CSS rules that convert by build:r2.

We corrected this in this page by overriding main_rtl.css  : 

http://dev.liferayportal.ir/%DA%AF%DB%8C%D8%AA-%D9%88-%DA%AF%DB%8C%D8%AA-%D9%87%D8%A7%D8%A8/-/knowledge_base/-/repository-github

![image](https://user-images.githubusercontent.com/4546637/57224676-71612600-701f-11e9-89fb-8435c2c1fe25.png)

Another example is when we have a navigation menu in the header and placed that to the left in LTR mode.
if we want to keep this menu in the left in RTL mode, what can we do?
build:r2 change position of this menu to Right automatically.

**Comment by jbalsas** [comment]
Hi @naderjafari, thanks for the examples! I'd like to point out that some things might seem like `Wrong CSS rules that convert by build:r2` when in reality they might be exposing some issues in your content.

For example, the `pre` element is directional and it will align based on the computed `dir` attribute of its containers as appropriate. 

If you add a css rule such as `pre { text-align: left; direction: ltr; }` you're basically saying that no matter what contents are inside a `pre` you want them to align on the left by default. You shouldn't even need to do this, because this is the default, and if the direction changes (as we do when the locale changes), then `pre` should be changing. As far as I saw it, the equivalent in rtl would be that no matter the contents inside a `pre` tag, you'd want them right aligned by default.

This, for example, could be controlled by `<pre dir="auto"` to detect the better alignment based on content, or specific values if the content is known. That way, css shouldn't even be necessary.

Your second example of course makes sense. It's hard for us, LTR users to understand how pages in RTL languages are read and used. Just so we can better understand it. Would that be the norm? That a navigation is always placed in the same position regardless the direction of the text?

Thanks for all the useful information you're providing! :)

**Comment by izaera** [comment]
> Your second example of course makes sense. It's hard for us, LTR users to understand how pages in RTL languages are read and used. Just so we can better understand it. Would that be the norm? That a navigation is always placed in the same position regardless the direction of the text?

I've been investigating this in an Android device (forcing RTL layout in developer options) and it looks like Google products, Twitter and Instagram mirror the whole UI. That means that the hamburger icon, for example, is moved to the right. So, I guess, we are following the standard/recomended behaviour when converting to RTL. 

However, I understand that people may want to make their own design decisions and we should provide a way for them to implement them. There is probably room for exceptions in RTL mirroring...

**Comment by izaera** [comment]
See [this comment](https://github.com/liferay/liferay-js-themes-toolkit/pull/331#issuecomment-578801424) for information on why this issue is being closed without resolution.
