### ISSUE TITLE
Typo in MIME type for javascript files in watch mode

### ISSUE THREAD

**Issue by sumnerwarren** [liferay/liferay-js-themes-toolkit#349]
An incorrect MIME type is being returned for JS files in watch mode. You can see this running `gulp watch` and executing a curl similar to:

```
➜ curl -I http://localhost:9080/o/theme-name/js/main.js
HTTP/1.1 200 OK
Content-Type: text/javacript
Date: Fri, 07 Jun 2019 12:52:59 GMT
Connection: keep-alive
```

Note the Content-Type of **text/javacript** instead of **text/javascript**.

**Comment by wincent** [comment]
Good catch. Thanks for spotting and fixing this.
