### ISSUE TITLE
lx-icon Sass function does not generate in 7.1

### ISSUE THREAD

**Issue by fortunatomaldonado** [liferay/liferay-js-themes-toolkit#359]
Reproduce:
1. Build 7.1 theme
2. Add the following code in `_custom.scss`
```
.angle-right { 
        background-image: lx-icon(angle-right, #fff); 
}
```
3. Build the theme

Expected Behavior: The css/main.css file updates `.angle-down` with svg statements
Actual Behavior: The css/main.css still contain `lx-icon(angle-right, #fff);`

Let me know if there are any questions or comments about this.
Thank you.

**Comment by wincent** [comment]
Not super familiar with this, @fortunatomaldonado, but would `clay-icon(angle-right, #fff)` work?

I see `$lx-icons` as a variable, not a mixin. It's defined in `node_modules/clay-css/src/scss/functions/_global-functions.scss` inside my test theme, and the `clay-icon()` function which uses appears a few lines above that. (Having said that, this may not be a 7.1 theme; it's just the one I happen to have handy right now).

**Comment by jbalsas** [comment]
@pat270, could you offer some insight here? What’s expected?

**Comment by wincent** [comment]
Ah, my grepping sucks. I was looking at `$lx-icons`, but there is indeed an `lx-icon()` mixin, defined in `packages/liferay-theme-deps-7.0/node_modules/liferay-frontend-theme-unstyled/css/aui/lexicon/atlas-theme/variables/_forms.scss` (but note: that's in the 7.0 deps... so we must have changed something in 7.1).

**Comment by wincent** [comment]
https://github.com/liferay/clay/commit/850eb0582d1ea808771d9578e195e91f3115e1c0

**Comment by fortunatomaldonado** [comment]
Hello @wincent,

`clay-icon(angle-right, #fff)` does indeed work. Thank you for finding the changes, truly appreciate the help!
