### ISSUE TITLE
Provide scripts and use local gulp

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-js-themes-toolkit#381]
Currently, themes rely on a global gulp installation to work even though we set `gulp` as a dependency.

We might want to provide a `scripts` section so after creating a theme one can simply `yarn|npm deploy` and get it running without relying on a global `gulp` binary

**Comment by wincent** [comment]
Sounds good. Once we do that, we should update [the docs](https://portal.liferay.dev/docs/7-1/tutorials/-/knowledge_base/t/creating-themes) (they currently tell people to "install Yeoman and gulp" but note that you can run Gulp out of `node_modules/.bin` if you don't want to global install). cc @mwilliams2014.

**Comment by mwilliams2014** [comment]
@wincent I mention in the note just below that they can use the local gulp in the node_modules folder:

> Note: Gulp is included as a local dependency in generated themes, so you are not required to install it. It can be accessed by running node_modules\.bin\gulp followed by the Gulp task from a generated theme’s root folder.

**Comment by wincent** [comment]
> I mention in the note just below that they can use the local gulp in the node_modules folder

Yep, I know you do 😁 ; that's what I meant when I said "they currently tell people to install ... but [they] note that you can run Gulp out of `node_modules`". My technical writing skills need work. 🤦‍♂️

**Comment by mwilliams2014** [comment]
Your writing is fine, apparently I need to improve my reading skills 😁
