### ISSUE TITLE
Wrong “Used by” metric in GitHub

### ISSUE THREAD

**Issue by yuchi** [liferay/liferay-js-themes-toolkit#396]
GitHub now shows the number of dependent projects in the “Used by” badge on top of the header of the project:

<img width="1047" alt="Schermata 2019-10-04 alle 17 57 40" src="https://user-images.githubusercontent.com/646609/66222026-82968780-e6d0-11e9-9e9b-e8f3b9c022d8.png">

As you can see it wrongly assumes only 3 other projects depend on it, which is wrong since you can see that almost [280 repos depend on `liferay-theme-tasks`](https://github.com/liferay/liferay-js-themes-toolkit/network/dependents?package_id=UGFja2FnZS0xODE4ODY5Ng%3D%3D). This is because they are showing the counter of the first package they found, which is `generator-liferay-theme`.

An administrator of this project [should be able to change the package to use for the counter.](https://twitter.com/olivtassinari/status/1179690054085726209)

**Comment by diegonvs** [comment]
@jbalsas, would be good update all our packages :)

**Comment by wincent** [comment]
I created this LRIT ticket to request that the change be made in this repo: https://issues.liferay.com/browse/LRIT-15623 (link probably won't be visible to others though because these IT tickets all get created with locked-down perms).

**Comment by wincent** [comment]
This has now been resolved.

**Comment by yuchi** [comment]
<img width="1552" alt="Schermata 2019-10-10 alle 15 36 27" src="https://user-images.githubusercontent.com/646609/66574068-e8bd5780-eb73-11e9-8a35-5affe27e9a80.png">
