### ISSUE TITLE
Layout generator - fs.readfileSync is not a function

### ISSUE THREAD

**Issue by Desperino** [liferay/liferay-js-themes-toolkit#409]
Hi guys,
layout generator throw this error:

> TypeError: fs.readfileSync is not a function

I think there is a misspelling error inside [this file](https://github.com/liferay/liferay-js-themes-toolkit/blob/2c0f7350e01b6763854c36b403baaa9e6042b80c/packages/generator-liferay-theme/generators/layout/index.js#L64).

fs.readfileSync should be fs.read**F**ileSync (F is uppercase).

I'm using node v10.12.0 on Windows.

Have a good time.

**Comment by wincent** [comment]
Thanks for catching that @Desperino! We'll publish a fixed version shortly.

**Comment by wincent** [comment]
Fix is available in v9.4.2.
