### ISSUE TITLE
Wrong <template-path> auto-generation

### ISSUE THREAD

**Issue by Desperino** [liferay/liferay-js-themes-toolkit#412]
Hi all,
when i'll try to create a new layout (example id: "foo") with ```yo liferay-theme:layout``` command, it's created a ```liferay-layout-templates.xml``` file with this content:

```
<layout-templates>
  <custom>
    <layout-template id="foo" name="foo">
      <template-path>\layouttpl\custom\foo-layouttpl/foo.ftl</template-path>
      <thumbnail-path>\layouttpl\custom\foo-layouttpl/foo.png</thumbnail-path>
    </layout-template>
  </custom>
</layout-templates>
```

If i deploy the layout, i see this error: **[LayoutTemplateLocalServiceImpl:369] No content found at template path ...**

This happens because ```<template-path>``` has backslashes (```\```) instead of slashes (```/```). I think it should be ```<template-path>/layouttpl/custom/foo-layouttpl/foo.ftl</template-path>``` (same for thumbnail-path).

If this is true, you could watch [here](https://github.com/liferay/liferay-js-themes-toolkit/blob/bdad65c47130f09193a66baad982e01f32cebd2e/packages/generator-liferay-theme/generators/layout/index.js#L142) the ```path.join``` function. It returns a [normalized path](https://nodejs.org/docs/latest/api/path.html#path_path_normalize_path) but i don't know if in this case it could be always correct.

I'm using Liferay Portal CE 7.2 GA1 bundled with Tomcat **on Windows**.

**Comment by wincent** [comment]
What we might actually need there is `path.posix.join()`. If you wanted to test that out locally by making a sneaky edit to your installed copy of the generator could you let me know if that fixes it for you?

**Comment by Desperino** [comment]
Yes, in my local copy this fix is correct. I tried to generate a new layout and i deployed it without errors.

**Comment by wincent** [comment]
Thanks for confirming, @Desperino.

**Comment by wincent** [comment]
v9.4.3 is now out with this fix.
