### ISSUE TITLE
Make build (R2) errors more obvious and recover from them gracefully

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-js-themes-toolkit#417]
From a customer report. When R2 chokes trying to RTLify files, the error message doesn't help that much figuring out what to do. 

```bash
...
[16:05:00] Starting 'build:r2'...
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: property missing ':' near line 857:1
...
```

Failures like this will stop the build. In addition to making the message more obvious, we should also try to recover gracefully and maybe just leave the css un-rtlified.

**Comment by jbalsas** [comment]
See other instances where we had to track invalid CSS down -> https://github.com/liferay/liferay-theme-tasks/issues/59#issuecomment-332135124

**Comment by wincent** [comment]
Are you sure we want to allow the build to "succeed" in the presence of an error? If we merely log a warning, it seems pretty likely that it will go ignored.

Do you have an example of the kind of input that can cause R2 to choke? It seems that if it is bad CSS then blowing up (with a much better error message) is the right thing to do; on the other hand, if the CSS is technically valid but R2 is still choking then I think it would be easier to justify trying to recover and proceed with the build.

**Comment by jbalsas** [comment]
Hey @wincent, I'll have to do a lot of digging to find an input example. It's usually a bit more convoluted than that, where apparently valid SASS will create invalid (unparseable) CSS. That's where `css-parse`, not `R2` per-se, chokes.

My reasoning behind allowing the build to succeed is that most companies don't care about R2 running as they won't run RTL-based sites in production. A company just running English sites won't necessarily need to even bother.

One thing I considered was to make RTL optional... in light of that future update, allowing the RTL process to succeed would be somewhat equivalent to opting-out of the feature all-together.
