### ISSUE TITLE
Add support for "Classic" extend

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-js-themes-toolkit#419]
As highlighted in [Limitations of Styled theme and usage of Classic](https://github.com/liferay/liferay-js-themes-toolkit/issues/90) and some [forum](https://liferay.dev/forums) threads, we'd like to explore a way to support getting a "Classic" look and feel out of the box when creating a new theme.

Our main stopper has always been exposing classic as an API that we would need to maintain rather than as a product which would limit a lot the type of changes we could apply to it from one version to another.

To this effect, I'd like to propose a mixed extend/kickstart approach where upon creation, we can prompt the user to extend from "Classic", but doing so will have a different effect than extending from other themes.

**Proposal**
- User runs `yo liferay-theme`
- Prompt theme shows the option to extend from `styled`, `unstyled`, `classic`
- If `classic` is selected
    - `parentTheme` is set to `styled`
    - A hard copy of [frontend-theme-classic/src](https://github.com/liferay/liferay-portal/tree/master/modules/apps/frontend-theme/frontend-theme-classic/src) is done in the new theme

This should effectively jumpstart developers to the point where they have a visually appealing theme without being locked to a specific version of it and being able to quickly adapt the existing changes.

/cc @marcoscv-work

**Comment by wincent** [comment]
Sounds like an improvement. Do you foresee any chance of users wanting to "update" an extended classic theme? This is kind of like create-react-app's `eject` operation, which is very clearly labeled as an irreversible operation, but with what you're proposing here the difference between extending `classic` and extending the other themes is implicit, not explicit.

**Comment by jbalsas** [comment]
Hey @wincent, that's a fair point, and that's exactly what we want to avoid. Allowing "updates" would basically mean we acknowledge it as an API and will expose it to bug reports which has always been what we've tried to avoid. (Keep in mind that we do honour API in `_unstyled` and `_styled` themes)

With this mechanism, I hope we can at least provide customers the feature they need without getting in the way of our changes for that theme.

One option to make it more explicit would be to add it to the `kickstart` command rather than the `extend` one since `kickstart` was a tad more explicit and kind of irreversible. See https://github.com/liferay/liferay-js-themes-toolkit/tree/master/packages/liferay-theme-tasks#kickstart

What do you think?

**Comment by wincent** [comment]
Adding it to `kickstart` seems more "honest". And we could point people in that direction from the `extend` prompt itself, or from the docs.

**Comment by jbalsas** [comment]
Sounds good to me... we have some approaches, I think:

### Approach 1
- User runs yo liferay-theme
- Prompt theme shows the option to extend from styled, unstyled, classic
- If classic is selected
    - A big warning is shown explaining what "extending" from classic means
    - parentTheme is set to styled
    - A hard copy of frontend-theme-classic/src is done in the new theme

### Approach 2
- User runs yo liferay-theme
- Prompt theme shows the option to extend from styled, unstyled, classic
- If classic is selected
    - A big warning is shown explaining what "extending" from classic means
    - parentTheme is set to styled
    - On completion of the theme creation, trigger `gulp kickstart`

### Approach 3
- User runs yo liferay-theme
- Prompt theme shows the option to extend from styled, unstyled, classic
- If classic is selected
    - A big warning is shown explaining that to use `classic`, please go and create a `styled` theme and then run manually `gulp kickstart...`

### Approach 4
... :think

**Comment by wincent** [comment]
Ah, I didn't pick up in your initial description that you were saying the `gulp extend`/`gulp kickstart` should be *baked into* theme creation rather than being a separate step as they currently are. If we're changing the semantics of what happens at creation time, then we're going to need something very obvious in the generator output and docs anyway, so any of your "big warning" options are probably ok. I'd probably shy away from using the word "extend" in the prompt because long-term theme creators may have a very specific idea about what that means (the prompt might be "What would you like to use as a base for your theme?").

However, if `extend` and `kickstart` are going to continue existing as independently runnable tasks, then we'll still need to decide on what to do if somebody insists on running one to `extend` classic (error? scary warning? scary warning + silent kickstart?).

🤷‍♂

**Comment by izaera** [comment]
How about letting everything as it is now: only allow users to extend from unstyled or styled and then, if the user selects unstyled, prompt whether he wants to kickstart classic on top of styled extension?

If we just want to provide the user with a "macro" operation, we shouldn't let it look like any other thing, IMO...

**Comment by izaera** [comment]
Apparently what most of the people want is to create a theme based on `classic` so we are going to reverse the questions.

We will first ask if the user wants to create a theme "based on classic":

- If the user says yes, we will explain him what that would do: create a theme extending from `styled` and then kickstart `classic` on top of it.

- If the user says no, we will then ask if he wants to extend from `styled` or `unstyled` as usual.
