### ISSUE TITLE
Support resources-importer in watch mode

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-js-themes-toolkit#45]
Based off of https://github.com/liferay/liferay-theme-tasks/issues/91 by @mouzofabricio

> I have a theme where i added some structures and templates.
>
> For some reasons the scss changes work perfectly with gulp watch but when I make changes on a template it doesn't update on the liferay instance.

> Well I was able to narrow down the issue.
>
> Apparently the portal_normal.ftl template is being updated correctly but the problem is with the resources-importer templates.

**Comment by wincent** [comment]
I believe this should be fixed in the current latest releases of the v8 and v9 branches.

At the time of writing, to get the latest v8 release you would `npm install --dev liferay-theme-tasks`, and to get the latest v9 release you would `npm install --dev liferay-theme-tasks@next`.
