### ISSUE TITLE
Provide an option (--config config.json) to pass in the configuration

### ISSUE THREAD

**Issue by david-truong** [liferay/liferay-js-themes-toolkit#455]
I would like to provide an option to pass in the configuration so we can skip the prompts similar to what is provided for liferay-js-toolkit.

This will allow us to programmatically invoke the generators for unit tests and for blade-cli without requiring a users input.

**Comment by jbalsas** [comment]
Hey @david-truong, which versions of the Toolkit will need this option? Can you provide an overview of the setup that will be integrating it?

**Comment by david-truong** [comment]
We will need it for 8.x and 9.x.

For blade have a project with the following package.json

8.x
```{
	"devDependencies": {
		"generator-liferay-theme": "8.1.2",
		"yo": "3.1.0"
	},
	"scripts": {
		"build-theme": "yo liferay-theme --skip-install",
		"import-theme": "yo liferay-theme:import --skip-install"
	},
	"version": "1.0.0"
}```

9.x
```
{
	"devDependencies": {
		"generator-liferay-fragments": "1.2.1",
		"generator-liferay-js": "2.18.2",
		"generator-liferay-theme": "9.5.0",
		"generator-liferay-theme-themelet": "1.2.0",
		"yo": "3.1.0"
	},
	"scripts": {
		"build-fragment": "yo liferay-fragments",
		"build-theme": "yo liferay-theme",
		"build-widget": "yo liferay-js"
	},
	"version": "1.0.0"
}```

and we run `$YO_PATH liferay-theme --config config.json`

**Comment by izaera** [comment]
See how this feature is used in https://github.com/liferay/liferay-js-themes-toolkit/pull/467

**Comment by izaera** [comment]
This has been tested and works, so I'm closing it.
