### ISSUE TITLE
liferay-theme-tasks 10.0.0-alpha.1+gulp 4.0.0 on Windows - Generated theme is deployed as a portlet instead of a theme, and it cannot be applied to site.

### ISSUE THREAD

**Issue by zhangyan0701** [liferay/liferay-js-themes-toolkit#458]
**Steps to reproduce:**

1. Generate a theme with JS Theme Toolkit v9.5.0.
2. Edit the theme's package.json and point liferay-theme-tasks to "10.0.0-alpha.1" and gulp to "^4.0.0".
3. rm -rf node_modules (just in case).
4. rm package-lock.json (just in case).
5. Run npm install again.
6. Navigate to theme's root folder.
7. Run 'gulp build'.
8. Copy the war file into portal/deploy.
9. Go to Control Panel > Component.

Expected Result:
The generated theme should be listed in Themes tab.

Actual Result:
The generated theme is listed in Portlets tab.
![not a theme](https://user-images.githubusercontent.com/25576873/78140857-3b116e00-745d-11ea-8bf8-9a29d2103e78.png)

**Comment by izaera** [comment]
Commented [this](https://github.com/liferay/liferay-js-themes-toolkit/pull/461#issuecomment-608332879) while investigating this issue, which seems closely related to #457.
