### ISSUE TITLE
Normalize file path handling

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-themes-toolkit#462]
Trying to fix #458 I've realised that we have problems with Windows vs POSIX paths as we had long ago in the JS Toolkit.

The root cause of #458 is that `gulp` needs glob expressions (as the ones passed to `gulp.src`) to be in POSIX format. But the globs are made based on the options received by `registerTasks`, which are provided by the user. So, if the user passes paths in Windows format, we need to convert them to POSIX before making the globs.

Also, the files `liferay-theme.json` and `liferay-plugin.json` have paths inside them that may need to be normalized too.

In the JS Toolkit I decided that every path in config files should be in POSIX format (even in Windows). This is because that way projects may be multiplatform and the same source can be used for Windows and POSIX systems. Then, the internal machinery of the JS Toolkit takes care of converting from POSIX to Windows when needed.

I would like to do the same in Themes Toolkit, but it may break compatibility with already existing projects. We may argue that because we are going to release a new major version it doesn't matter, but there's another possibility that we may use, namely that of using native paths in `registerTasks` and taking care to convert them to POSIX when needed (i.e: when running on Windows).

Still, as I said I prefer to always use POSIX paths in configuration to be multiplatform.

Opinions?

**Comment by wincent** [comment]
> In the JS Toolkit I decided that every path in config files should be in POSIX format (even in Windows). This is because that way projects may be multiplatform and the same source can be used for Windows and POSIX systems. Then, the internal machinery of the JS Toolkit takes care of converting from POSIX to Windows when needed.

I think this is pretty much the *only* way to do it, really. Especially in places where paths meet globs (and `\` is used to escape). So, for consistency, even in the absence of globs, I think using POSIX paths for config is the way to go.

**Comment by mwilliams2014** [comment]
At least in the case of the `liferay-theme.json`, I don't think the path format is a big issue on Windows (which I test one :-) ) because the path is automatically added for you based on the `init` tasks. If you need to change it, you can just re-run the `init` task. I'm not sure about `liferay-plugin.json`.

**Comment by izaera** [comment]
@mwilliams2014 `liferay-plugin.json` is the same as `liferay-theme.json` but for layouts. So, same rules should apply.
