### ISSUE TITLE
Backport --config option to v8

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-themes-toolkit#466]
This is backport of #455 to v8 and v9.

I'm not quite sure if v9 should be maintained or deprecated, given that v10 will target the same platforms... Any opinions? :thinking:

**Comment by wincent** [comment]
v9 should not be maintained; v10 *replaces* it.

v8 should be maintained. It does not have a replacement.

**Comment by izaera** [comment]
This was released as `v8.2.0` and has been tested by @david-truong, confirming that it works.

Closing.
