### ISSUE TITLE
 liferay-theme-tasks 10.0.0-alpha.2+gulp 4.0.0 - Message "webBundleDir": "watching" is not written into liferay-theme.json file after running 'gulp watch'

### ISSUE THREAD

**Issue by zhangyan0701** [liferay/liferay-js-themes-toolkit#468]
**Steps to reproduce:**

1. Generate a project with node 10 and the current generator (9.5.0).
2. Edit the project's package.json and point liferay-theme-tasks to "10.0.0-alpha.2" and gulp to "^4.0.0".
3 rm -rf node_modules (just in case).
4 rm package-lock.json (just in case).
5. Run npm install again.
6. Navigate to theme's root folder.
7. Make an edit to to file _custom.scss.
```
html body {
    background-color:green;
}
```
8. Run 'gulp deploy'.
9. Start liferay.
10. Apply theme to a site.
11. Navigate to theme’s root folder.
12. Run 'gulp watch'.
13. Check liferay-theme.json file.

Expected Result:
Message "webBundleDir": "watching" should be present in liferay-theme.json file.

Actual Result:
Message "webBundleDir": "watching" is not written into liferay-theme.json file.

**Comment by izaera** [comment]
:-o 

I removed that setting on purpose because it looked like some temporary thing but if you have tests for that it may be because it is necessary :sweat_smile: .

@zhangyan0701 Do you have an idea of why is it necessary that `webBundlerDir: watching` is written to the JSON file? 

Is there any tool reading (outside of the Themes Toolkit) that :thinking: ?

**Comment by izaera** [comment]
I have found a reference to `webBundleDir: watching` in [our docs](https://help.liferay.com/hc/es/articles/360018166691-Automatically-Deploying-Theme-Changes-).

**Comment by mwilliams2014** [comment]
I would say as long as the watch task itself works, that's what's most important. As far as the property being noted in our docs, I just noted it as a way to verify that it was running, but you can also verify that by simply making a change and verifying that it's auto-deployed. So, in our 7.2/7.3 Liferay Learn docs, I can make sure that note is removed. Thanks @izaera

**Comment by izaera** [comment]
So, I'll close this as `wontfix` tomorrow and will release v10.0.0 so that we can deprecate v9.0.0 and that way we only have to maintain two branches: v8 and v10.

Otherwise this is going to be a nightmare :grimacing: .

**Comment by wincent** [comment]
Yeah, the intention was never to maintain 3 branches. Just 8.x for older versions of DXP, and then > 8 for everything newer. Ideally we would have stayed on v9 for longer before making a breaking change, but ultimately, our hand was forced...
