### ISSUE TITLE
Clean up dist tags

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-js-themes-toolkit#473]
With the release of 10.0.0 ([liferay-theme-tasks](https://github.com/liferay/liferay-js-themes-toolkit/releases/tag/liferay-theme-tasks%2Fv10.0.0), [generator-liferay-theme](https://github.com/liferay/liferay-js-themes-toolkit/releases/tag/generator-liferay-theme%2Fv10.0.0)), and the creation of [the `9.x` maintenance branch](https://github.com/liferay/liferay-js-themes-toolkit/tree/9.x), I tried to create a "9.x" tag to match the "8.x" tag that we already have for the v8.x series.

Turns out, NPM has tightened up their checks and you can no longer do this (you get `Tag name must not be a valid SemVer range: 9.x`). I had forgotten, if I ever knew, that NPM treats strings like "9.x" as [valid range specifiers](https://docs.npmjs.com/misc/semver) (ie. "9.x" is shorthand for ">= 9.0.0 < 10.0.0".

As such, not only do we not need `9.x` as a tag; we don't need `8.x` either. A command like `yarn add generator-liferay-theme@8.x` will behave basically the same with or without the tag. So, as step one, let's just delete the tags.

You might think that, if anything, this is better than having tags because its one less thing to do when you release a package on a maintenance branch like 8.x or 9.x. However, it is not all roses: if you cut 10.0.0, as we just did, and then cut 9.5.1 (as we are about to do), then the `latest` tag, which NPM maintains by default, will actually point at 9.5.1, which may be a bit misleading. Sure, it is literally the last-published version, but it is not the "most current" code in terms of accrued development.

As such, we *may* still need tags for those old branches. That would work ok in this repo because we are not using `liferay-js-publish` on the 8.x and 9.x branches. Tagging (or not) on those branches is still something you can explicitly do, because running `yarn publish` [is a manual process](https://github.com/liferay/liferay-js-themes-toolkit/blob/50c717b5a4d76168ef45ae1363a85c0cb16034da/CONTRIBUTING.md).

These are the packages with "excess' tags:

- https://www.npmjs.com/package/liferay-theme-tasks?activeTab=versions
- https://www.npmjs.com/package/generator-liferay-theme?activeTab=versions
- https://www.npmjs.com/package/liferay-theme-mixins?activeTab=versions

To remove them:

```
npm dist-tag rm liferay-theme-tasks 8.x
npm dist-tag rm liferay-theme-tasks next
npm dist-tag rm liferay-theme-tasks prerelease
npm dist-tag rm liferay-theme-mixins 8.x
npm dist-tag rm liferay-theme-mixins next
npm dist-tag rm generator-liferay-theme 8.x
npm dist-tag rm generator-liferay-theme next
npm dist-tag rm generator-liferay-theme prerelease
```

Next step would be to add explicit tags to the older package releases, probably `maint-8.x` and `maint-9.x`. I don't know that we would need to update any documentation out there that currently advises to install `generator-liferay-theme@8.x` (etc), because that will work as-is without the tag.

In the end, I think that adding extra tags doesn't really help us because we still can't control what `latest` points at in any direct way (ie. if we release a patch to 9.x, we shouldn't be forced do release an empty patch to 10.x as well just to make sure 10.x is always `latest`), so I am leaning towards not having any extra tags.

**Comment by wincent** [comment]
I already did the `npm dist-tag rm` stuff. If you agree with my analysis, @izaera, specifically the following:

> I think that adding extra tags doesn't really help us because we still can't control what `latest` points at in any direct way (ie. if we release a patch to 9.x, we shouldn't be forced do release an empty patch to 10.x as well just to make sure 10.x is always `latest`), so I am leaning towards not having any extra tags.

Then I think we can close this issue as completed.

**Comment by wincent** [comment]
Obvious exception to the "don't need explicit" tags guideline is prereleases, which get a `prerelease` tag thanks to [this line](https://github.com/liferay/liferay-npm-tools/blob/1f0def7796b997eb4269477c9f5178fc4f3b17d2/packages/liferay-js-publish/src/index.js#L201) in `liferay-js-publish`.

**Comment by izaera** [comment]
I'm not sure if I understood correctly :thinking: 

The only reason that we want to control what `latest` is pointing to is so that people doing:

```shell
$ npm install generator-liferay-js ⮨
```

Other than that it's not really that useful.

That's the reason why we tag alphas with `prerelease`. It's not that we care about `prerelease` at all (it could be designed as `the-well` too and it would work), it's that we don't want the latest alpha to be installed when someone runs the above command.

So I guess we could do it with three tags:

1) `latest` automatically managed by npm and always pointing to v10
2) `maintentance` for v8 and v9 releases
3) `prerelease` for alphas

And if we wanted to make it simpler, we could gather 2 and 3 into one single tag (`dark-hole` or something similar).

**Comment by izaera** [comment]
We can configure the dist-tag to use by liferay-js-publish in its configuration file, given that we have different branches for different version lines. So, the config file in `9.x` branch would carry information for `liferay-js-publish` to tag everything as `maintenance` (unless it is a `prerelease`).

Does that make sense?

**Comment by wincent** [comment]
> Other than that it's not really that useful.

Correct. Tagging might not have any uses, but this particular one is *incredibly important*. Given that v8, v9 and v10 are mutually incompatible, it would be pretty bad if you got one or the other depending on the time and date that you ran `npm install`... To provide a stable environment, we need to make sure that `latest` only ever points at one series.

> We can configure the dist-tag to use by liferay-js-publish in its configuration file.

Hehe. There is no configuration file. At most, it looks at the `.yarnrc` to figure out version tags and prefixes. I believe, however, that we can pass arbitrary default commandline arguments to `yarn` as described [here](https://classic.yarnpkg.com/en/docs/yarnrc/#toc-cli-arguments). That means something like a top-level `.yarnrc` in the root of the 8.x and 9.x branches (they don't use per-package configs, and they don't even have a root-level config yet) has a good chance of working:

```
--publish.tag maintenance
```

I'll give that a test and see if it works.

**Comment by wincent** [comment]
Ok, tested this with my trusty [wincent-test-package](https://www.npmjs.com/package/wincent-test-package?activeTab=versions):

```
mkdir demo
cd demo
yarn init -y
yarn add wincent-test-package
echo '--publish.tag maintenance' > .yarnrc
cd node_modules/wincent-test-package
```

ie. simulating a monorepo layout where the `.yarnrc` is higher in the directory hierarchy.

Cut a release:

```
yarn version --patch # bumps version from 1.0.0 to 1.0.1
yarn publish
```

If you look at the [versions tab](https://www.npmjs.com/package/wincent-test-package?activeTab=versions), you see the `maintenance` tag was correctly applied to v1.0.1, and v1.0.0 retained the `latest` tag.

Now, cut a prerelease:

```
yarn version --prepatch # bumps version to 1.0.2-0
yarn publish --tag prerelease # this is what `liferay-js-publish` would do
```

Now the versions tab shows that v1.0.2-0 correctly got the `prerelease` tag; ie. command-line arguments trump what's in the `.yarnrc`:

![CleanShot 2020-04-15 at 15 23 00@2x](https://user-images.githubusercontent.com/7074/79342102-03122c80-7f2d-11ea-9b86-cd195498d0b5.png)

So, all up, I'd say this is going to work. I'll send PRs to the 9.x and 8.x branches now.

**Comment by izaera** [comment]
Good :-). 

I forgot that it was yarn who needed to receive the dist-tag, not liferay-js-publish. But glad to have inspired something :sweat_smile:

**Comment by wincent** [comment]
PRs are up at:

- https://github.com/liferay/liferay-js-themes-toolkit/pull/474
- https://github.com/liferay/liferay-js-themes-toolkit/pull/475

**Comment by wincent** [comment]
You might think this one would have autoclosed because https://github.com/liferay/liferay-js-themes-toolkit/pull/475 has a "Closes:" annotation in it, but GitHub only autocloses for PRs/commits that get merged to `master`, and that PR and its companion go to `8.x` and `9.x` respectively, so I'm going to close this one by hand.

**Comment by izaera** [comment]
Yes. That's the reason why I have to manually close every issue in JS Toolkit...
