### ISSUE TITLE
Temporary compile-css files race condition

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-themes-toolkit#485]
Currently the build process creates a temporary `_bourbon.scss` file in `/tmp/tmp` which may lead to race conditions if several builds are run in parallel.

These files [were created inside `node_modules`](https://github.com/liferay/liferay-js-themes-toolkit/blob/fe8c7c5348fb47cb757a8f476fab0d784804545f/packages/liferay-theme-tasks/lib/bourbon_dependencies.js#L25) in previous versions of the project, what seems a quite dirty technique. 

That was the reason why it was changed introducing this bug exactly in [this modification](https://github.com/liferay/liferay-js-themes-toolkit/commit/bb63f0d023517c84202bf3c5efaa76f77c8e34a5#diff-fb29d65ae0a3361a552dfb08f9d72ff0R25).

**Comment by izaera** [comment]
BTW: this was detected during a portal's CI build (see https://github.com/izaera/liferay-portal/pull/138)

**Comment by wincent** [comment]
🤦‍♂️ — and the "dirty technique" [was in use for 5 years](https://github.com/liferay/liferay-js-themes-toolkit/commit/c8e77d6ab6e4f77505d5a48a5ef98d2e4509866d) 😂

**Comment by izaera** [comment]
Yes :shrug:
