### ISSUE TITLE
Font Awesome Version

### ISSUE THREAD

**Issue by sgreco-dev** [liferay/liferay-js-themes-toolkit#508]
The liferay-font-awesome package being used is using version 3.2.1 of Font Awesome, which is pretty out dated at this point.

Is there any way to update the version of Font Awesome that gets installed using the theme generator?  My only thought at this point is to create a theme without font awesome and manually install font awesome as a dependency of the theme.  Is this the suggested route if there is no way to update the liferay-font-awesome package?

**Comment by wincent** [comment]
> My only thought at this point is to create a theme without font awesome and manually install font awesome as a dependency of the theme. Is this the suggested route if there is no way to update the liferay-font-awesome package?

That sounds like a reasonable approach to me. If I had to guess, I'd say that the reason why the Font Awesome dependency isn't aggressively updated is that the major version updates contain breaking changes (things like icon names changing), and I imagine we can't update without effectively propagating that breakage to users. But that's just me speculating; I think @marcoscv-work or @jbalsas will know the definitive answer for sure, as well as have an idea about when/whether/if an update is likely in the future.

**Comment by jbalsas** [comment]
> Is there any way to update the version of Font Awesome that gets installed using the theme generator? My only thought at this point is to create a theme without font awesome and manually install font awesome as a dependency of the theme. Is this the suggested route if there is no way to update the liferay-font-awesome package?

I'd say that's the correct approach. We're no planning on making any further updates of FontAwesome. We've removed all of our internal dependencies with the icon font and it will be up to customers to decide if they want to add it or not.

**Comment by sgreco-dev** [comment]
Great, just wanted to make sure we were approaching it correctly.  Sounds like this will work just fine.
