### ISSUE TITLE
npm package missing version 

### ISSUE THREAD

**Issue by smallma876** [liferay/liferay-js-themes-toolkit#528]
Hello I installed jsPdf in my React-Widget and when its deployed these errors are generated in browsers console: 

 Missing dependency ':ERROR:Missing version constraints for pdfproyectoprueba$fs in package.json of pdfproyectoprueba$jspdf@2.1.1' of 'pdfproyectoprueba$jspdf@2.1.1/dist/jspdf.node.min'
    · Missing dependency ':ERROR:Missing version constraints for pdfproyectoprueba$path in package.json of pdfproyectoprueba$jspdf@2.1.1' of 'pdfproyectoprueba$jspdf@2.1.1/dist/jspdf.node.min'.

I generate my project with "yo liferay-js".
I have the next dependencies: 

"devDependencies": {
		"liferay-npm-bundler": "^2.18.8",
		"liferay-npm-build-support": "^2.18.8",
		"copy-webpack-plugin": "4.6.0",
		"webpack": "4.29.6",
		"webpack-cli": "3.3.0",
		"webpack-dev-server": "3.2.1",
		"babel-cli": "6.26.0",
		"babel-preset-env": "1.7.0",
		"babel-preset-react": "6.24.1",
		"babel-loader": "7.1.5"
	},
	"dependencies": {
		
		"jspdf": "^2.1.1",
		
		"react": "16.8.6",
		"react-dom": "16.8.6"
	},

Thank you for your help.

**Comment by izaera** [comment]
Wrong repo: this is the Themes Toolkit, not the JS Toolkit :-)

Please file your issue in https://github.com/liferay/liferay-frontend-projects/ and also provide more information like, for example, a github repo or ZIP file where the issue can be reproduced.

Thx.
