### ISSUE TITLE
Cannot update packages caused by vulnerabilities for newly created theme

### ISSUE THREAD

**Issue by john-co** [liferay/liferay-js-themes-toolkit#70]
john-co@john-co:~/my-liferay-theme$ npm audit fix
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

> liferay-theme-deps-7.0@8.0.0-beta.4 install /home/john-co/my-liferay-theme/node_modules/liferay-theme-tasks/node_modules/liferay-theme-deps-7.0
> node scripts/install.js

npm WARN my-liferay-theme@1.0.0 No description
npm WARN my-liferay-theme@1.0.0 No repository field.
npm WARN my-liferay-theme@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ liferay-theme-tasks@8.0.0-beta.4
added 1 package from 1 contributor and updated 1 package in 5.446s
fixed 24 of 43 vulnerabilities in 9484 scanned packages
  14 vulnerabilities required manual review and could not be updated
  1 package update for 5 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)
john-co@john-co:~/my-liferay-theme$ npm audit fix --force
npm WARN using --force I sure hope you know what you are doing.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> fsevents@1.2.4 install /home/john-co/my-liferay-theme/node_modules/fsevents
> node install

npm WARN my-liferay-theme@1.0.0 No description
npm WARN my-liferay-theme@1.0.0 No repository field.
npm WARN my-liferay-theme@1.0.0 No license field.

+ gulp@4.0.0
added 206 packages from 120 contributors, updated 16 packages and moved 2 packages in 6.933s
fixed 8 of 43 vulnerabilities in 9484 scanned packages
  35 vulnerabilities required manual review and could not be updated
  1 package update for 5 vulns involved breaking changes
  (installed due to `--force` option)

**Comment by john-co** [comment]
Note: the issue was observed in linux environment

**Comment by wincent** [comment]
Consolidating all dependency security stuff in https://github.com/liferay/liferay-js-themes-toolkit/issues/199
