### ISSUE TITLE
liferay-theme-deps-7.1 is left when reverting 7.1 theme to 7.0

### ISSUE THREAD

**Issue by mwilliams2014** [liferay/liferay-js-themes-toolkit#77]
1. run `gulp upgrade` to upgrade 7.0 theme to 7.1. Package.json shown below:
        "version": "7.1"
	},
	"devDependencies": {
		"gulp": "^3.9.1",
		"liferay-theme-tasks": "8.0.0-beta.5",
		"liferay-theme-deps-7.1": "8.0.0-beta.5"
	},
2. run `gulp-upgrade:revert` to revert theme back to 7.0. Package.json shown below:
        "version": "7.0"
	},
	"devDependencies": {
		"gulp": "^3.9.1",
		"liferay-theme-tasks": "8.0.0-beta.5",
		"liferay-theme-deps-7.0": "8.0.0-beta.5",
		"liferay-theme-deps-7.1": "8.0.0-beta.5"
	},

`liferay-theme-deps-7.1": "8.0.0-beta.5` should no longer be in reverted 7.0 theme

**Comment by jbalsas** [comment]
Hey @mwilliams2014, I was wondering what the `7.0` theme had in its `package.json` before triggering the `upgrade` process. 

I assume it already has `tasks` pointing to `8.0.0-beta.5`, but maybe it had `*-theme-deps-7.1` pointing to something other than `8.x`. In that case, I'd expect it to be back to the original values.

Could you or @john-co confirm that?

Thanks!

**Comment by mwilliams2014** [comment]
@jbalsas confirmed that this does not happen with a fresh 7.0 theme. this only happened when I imported a 6.2 theme, upgraded it to 7.0, then to 7.1, then back to 7.0.

Confirmed, your suspicions are correct 👍 The freshly imported 6.2 theme has the following `package.json`:


{
	"name": "lunar-resort-ce-theme",
	"version": "1.0.0",
	"main": "package.json",
	"keywords": [
		"liferay-theme"
	],
	"liferayTheme": {
		"baseTheme": "styled",
		"screenshot": "",
		"rubySass": true,
		"templateLanguage": "ftl",
		"version": "6.2"
	},
	"devDependencies": {
		"gulp": "^3.9.1",
		"liferay-theme-tasks": "8.0.0-beta.5",
		"liferay-theme-deps-6.2": "7.0.0",
		"liferay-theme-deps-7.0": "8.0.0-beta.5",
		"liferay-theme-deps-7.1": "8.0.0-beta.5"
	}
}

When you upgrade the theme to 7.0, it has the following:

		"version": "7.0"
	},
	"devDependencies": {
		"gulp": "^3.9.1",
		"liferay-theme-tasks": "8.0.0-beta.5",
		"liferay-theme-deps-7.0": "8.0.0-beta.5",
		"liferay-theme-deps-7.1": "8.0.0-beta.5"
	}
}

And finally the upgrade to 7.1, has the following:

		"version": "7.1"
	},
	"devDependencies": {
		"gulp": "^3.9.1",
		"liferay-theme-tasks": "8.0.0-beta.5",
		"liferay-theme-deps-7.1": "8.0.0-beta.5"
	}

So, naturally, the revert brings back the 7.1 theme deps since it was present in the 7.0 theme. 

Perhaps the issue here is that the 6.2 theme had the 7.1 theme deps when it was first imported. What do you think @jbalsas ?

**Comment by jbalsas** [comment]
Looking at this, only `6.2` themes can actually be imported, so it doesn't really make sense to push the `7.1` dependency on them, because they won't be upgrading. Probably we shouldn't even need the `*-deps-7.0` until we attempt an upgrade, at which point this should be automatic... 🤔

**Comment by jbalsas** [comment]
I can confirm that seems to work just fine. The only problem I'm still seeing is that we're setting `"rubySass": true,` by default, so in the end we can either: set it to `false` by default, or we should add the `gulp-ruby-sass` dependency... what do you think?

**Comment by mwilliams2014** [comment]
Yeah. I think setting `rubysass: false` by default and leaving that up to the developer is the best route. The only issue would be if rubysass reverts to false if the value is true when you upgrade. See https://github.com/liferay/liferay-themes-sdk/issues/37
