### ISSUE TITLE
gulp watch broken on Windows 10

### ISSUE THREAD

**Issue by chrberndt** [liferay/liferay-js-themes-toolkit#95]
## Environment ##

Win 10 Pro
Oracle JDK 1.8.0_181
Liferay DXP 7.1.10-ga1

Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ Node.js version
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory
√ npm version
√ yo version

Everything looks all right!
+ gulp@3.9.1
+ yo@2.0.5
+ generator-liferay-theme@8.0.0-beta.5

## How to reproduce ##

1. Download and unpack 7.1.10 GA1  bundle
1. include-and-override=portal-developer.properties in portal-ext.properties
1. launch Liferay with LIFERAY_HOME/tomcat-9.0.6/bin/startup.sh
1. Deploy valid activation key
1. Create theme as documented at  https://dev.liferay.com/de/develop/tutorials/-/knowledge_base/7-1/creating-themes (yo liferay-theme - with default settings)
1. cd my-liferay-theme/
1. deploy with gulp watch
1. telnet localhost 11311
1. start my-liferay-theme bundle 
1. Login to Liferay
1. select "My Liferay Theme"
1. set Resource Modification Check = 0 (Control Panel -> Configuration -> System Settings -> Platform -> Template Engines
1. mkdir src/templates
1. cp build/templates/portal_normal.ftl src/templates
1. modify src/templates/portal_normal.ftl
1. reload browser - first modification is reflected in browser
1. modify src/templates/portal_normal.ftl
1. reload browser - subsequent modifications are not reflected in browser

**Comment by chrberndt** [comment]
When I try to stop `gulp watch` with `CTRL+C` and try to restart afterwards, the symptoms are the same as reported here: https://github.com/liferay/liferay-themes-sdk/issues/18

**Comment by chrberndt** [comment]
Hey @jbalsas - anything new on this?

**Comment by fstendardi** [comment]
Any news about a possible solution or workaround?

**Comment by wincent** [comment]
https://github.com/liferay/liferay-js-themes-toolkit/pull/190 was just merged which should fix a number of watch-related problems. There is some follow-up still to do but we expect to be cutting a new v8 release candidate release shortly (most likely within a week or two). cc @julien

**Comment by wincent** [comment]
We have significantly changed the watch implementation in #190 with the hope of fixing the existing issues. At the time of writing, that's in the "master" branch and will be included in the next release (v8.0.0-rc.4). The master issue for tracking the rewrite is #127, so I am going to close these separate tickets and ask that we consolidate further discussion about watch there.
